name: all_dogs
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.6
  carousel_slider: ^4.1.1
  dio: ^4.0.6
  get: 4.6.5
  get_it: ^7.2.0
  get_storage: ^2.0.3
  image_picker: ^0.8.5+3
  flutter_svg: ^1.1.5
  intl: ^0.17.0
  like_button: ^2.0.5
  smooth_page_indicator: ^1.0.0+2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
